export enum Actions {
    SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN",
    SET_NOTES = "SET_NOTES",
    SET_DISPLAY_NOTES = "SET_DISPLAY_NOTES",
    SET_SORT_DISPLAY_NOTES = "SET_SORT_DISPLAY_NOTES",
    SET_SELECTED_NOTE = "SET_SELECTED_NOTE",
    SET_SEARCH_INPUT = "SET_SEARCH_INPUT",
    SET_SHOULD_TITLE_BE_AUTOFOCUSED = "SET_SHOULD_TITLE_BE_AUTO_FOCUSED",
    SET_IS_DATA_FETCHING = "SET_IS_DATA_FETCHING",
    SET_IS_DISPLAY_AUTH_FORM = 'SET_IS_DISPLAY_AUTH_FORM', 
    SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR', 
}